apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-instrumentation-mcp

resources:
- deploy.yaml
- service.yaml
- otel-collector.yaml
- redis-deployment.yaml
- redis-service.yaml

generatorOptions:
  disableNameSuffixHash: true
