---
apiVersion: v1
kind: Service
metadata:
  name: otel-instrumentation-mcp-svc
  labels:
    app: otel-instrumentation-mcp
spec:
  type: ClusterIP
  ports:
    - name: mcp-sse
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: otel-instrumentation-mcp
