---
# Add 'documentation' label to any change to *.md files
documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

# Add 'docker' label to any change in docker related files
docker:
  - changed-files:
      - any-glob-to-any-file: ["**/Dockerfile*", "**/.dockerignore"]

# Add 'kubernetes' label to any change in docker related files
kubernetes:
  - changed-files:
      - any-glob-to-any-file: ["manifests/**"]

# Add 'github_actions' label to any change .github/ directory
github_actions:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

# Add 'python' label to any change *.py files
python:
  - changed-files:
      - any-glob-to-any-file: ["**/*.py", "uv.lock", "pyproject.toml"]

# Add 'build' to any app code, taskfile, and goreleaser
build:
  - changed-files:
      - any-glob-to-any-file: ["Taskfile", ".goreleaser.yaml"]

# Add 'tests' to any tests
tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
