apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  labels:
    app: redis-cache
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: opentelemetry-instrumentation
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-cache