name: Bug report
description: Create a report to help us improve
title: "Bug: "
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure
        to fill out the entire form below, providing as much context as you can
        in order to help us triage and track down your bug as quickly as
        possible.

        Before filing a bug, please be sure you have searched through [existing
        bugs](https://github.com/liatrio-labs/otel-instrumentation-mcp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug)
        to see if an existing issue covers your bug.
  
  - type: dropdown
    id: component
    attributes:
      label: Component(s)
      description: Which component(s) does your bug report concern?
      multiple: true
      options:
        - SSE Deprecation
        - Authentication
        - Tools
        - Prompts
        - HTTP Streaming
        - Local Development
        - CI/CD
        - Kubernetes
        - Observability
        - Performance
        - Documentation
  
  - type: textarea
    attributes:
      label: What happened?
      description: Please provide as much detail as you reasonably can.
      value: |
        ## Description

        ## Steps to Reproduce

        ## Expected Result

        ## Actual Result
    validations:
      required: true
  
  - type: input
    attributes:
      label: API version
      description: What version did you use? (e.g., `v0.4.0`, `1eb551b`, etc)
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Environment information
      description: Please provide any additional information about your installation.
      value: |
        ## Environment
        OS: (e.g., "Ubuntu 20.04")
        Python version (if applicable): (e.g., "3.13")
        Kubernetes version (if applicable): (e.g., "v1.33.0")
  
  - type: textarea
    attributes:
      label: Configuration
      description: Please provide the configuration you are using (with sensitive information redacted).
      render: yaml
  
  - type: textarea
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output.
      render: shell
  
  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it.</sub>
      default: 0
