---
name: Lint Python

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6
        with:
          version: "0.8.0" # https://github.com/go-task/task
      
      - name: Install Task
        uses: alexellis/arkade-get@master
        with:
          task: v3.44.0 # https://github.com/go-task/task

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: '1.24'

      - name: Run linting
        run: task lint

      - name: Check License Headers
        run: |
          task addlicense
          if ! git diff --quiet -- . ':!uv.lock'; then
            echo "Files are outdated. Changes detected."
            echo "Please run 'task addlicense' and 'task lint' locally and commit the changes."
            exit 1
          fi
