---
name: Test Python

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.8.0" # https://github.com/go-task/task
      
      - name: Install Task
        uses: alexellis/arkade-get@master
        with:
          task: v3.44.0 # https://github.com/go-task/task

      - name: Run tests
        run: task test
