---
name: Test Python

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          version: "0.12.10" # https://github.com/go-task/task
      
      - name: Install Task
        uses: alexellis/arkade-get@5594ddff52ec7b8a71efd73acaa9e52936e35e16 # master
        with:
          task: v3.44.0 # https://github.com/go-task/task

      - name: Run tests
        run: task test
